server:
  port: 0

spring:
  application:
    name: my-2nd-service

eureka:
  
  # ??? instance-id ??
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://192.168.0.21:8761/eureka
      defaultZone: http://localhost:8761/eureka